version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Installing dependencies..."
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt
      - pip3 install pysqlite3
      - pip3 install pysqlite3-binary
      - echo "Run Test"
      - python manage.py test
artifacts:
  files:
    - '**/*'